force-app/main/default/objects/logSettings__c/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Disables this logging functionality.</inlineHelpText>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/logSettings__c/fields/Logging_Level__c.field-meta.xml
<CustomField>
    <fullName>Logging_Level__c</fullName>
    <description>ERROR, WARNING, INFO, DEBUG</description>
    <inlineHelpText>Must be one of the following; ERROR, WARNING, INFO, DEBUG.</inlineHelpText>
    <label>Logging Level</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/logSettings__c/fields/retention__c.field-meta.xml
<CustomField>
    <fullName>retention__c</fullName>
    <inlineHelpText>Nuber of days logs can persist for.</inlineHelpText>
    <label>Retention (days)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LoggingEngine_SettingsHandler.cls
public with sharing class LoggingEngine_SettingsHandler {
  public static Boolean enabled = false;
  public static String loggingLevel = 'INFO';
  public static Integer retentionPeriod = 365;

  static {
    getSettings();
  }

  public static void getSettings() {
    List<logSettings__c> logSettingsList = [
      SELECT Id, 
      enabled__c, 
      logging_level__c, 
      retention__c
      FROM logSettings__c
      LIMIT 1
    ];

    logSettings__c logSettings = logSettingsList.isEmpty() ? new logSettings__c() : logSettingsList[0];
    if(logSettings.id != null) {
        if(logSettings.logging_level__c != null){
            LoggingEngine_SettingsHandler.enabled = logSettings.enabled__c;
        }
        if(logSettings.logging_level__c != null){
            LoggingEngine_SettingsHandler.loggingLevel = logSettings.logging_level__c;
        }
        if(logSettings.retention__c != null){
            LoggingEngine_SettingsHandler.retentionPeriod = Integer.valueOf(logSettings.retention__c);     
        }
    }     
  }

  public static Integer getRetentionPeriod() {
    return retentionPeriod;
  }
}