force-app/main/default/objects/logSettings__c/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Disables this logging functionality.</inlineHelpText>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/logSettings__c/fields/Logging_Level__c.field-meta.xml
<CustomField>
    <fullName>Logging_Level__c</fullName>
    <description>ERROR, WARNING, INFO, DEBUG</description>
    <inlineHelpText>Must be one of the following; ERROR, WARNING, INFO, DEBUG.</inlineHelpText>
    <label>Logging Level</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/logSettings__c/fields/retention__c.field-meta.xml
<CustomField>
    <fullName>retention__c</fullName>
    <inlineHelpText>Nuber of days logs can persist for.</inlineHelpText>
    <label>Retention (days)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LoggingEngine_TestUtil.cls
@isTest
public class LoggingEngine_TestUtil {

    public static void upsertLogSettings(Boolean enabled, String logLevel, Integer retentionPeriod) {
        logSettings__c logSettings = new logSettings__c();
        
        try{
            logSettings = [SELECT Id FROM logSettings__c LIMIT 1];
        } catch (QueryException e) {
            System.debug(LoggingLevel.INFO,'No logSettings__c record found. Creating a new one.');
        }

        logSettings.enabled__c = enabled;
        logSettings.logging_level__c = logLevel;
        logSettings.retention__c = retentionPeriod;
        upsert logSettings;
    }

    public static void testData_createAccounts(Integer numAccounts) {
        List<Account> accounts = new List<Account>();
        for (Integer i = 0; i < numAccounts; i++) {
            accounts.add(new Account(Name = 'Test Account ' + i));
        }
        insert accounts;
    }

}